### ISSUE TITLE
in kvm machine , it fail to pass init 

### ISSUE THREAD

**Issue by AUGxhub** [lf-edge/edge-home-orchestration-go#81] opened 2020-03-10 09:04 UTC
**Describe the bug**
AS title shows 

**To Reproduce**

set up docker env on kvm based VM , and get key , user id ready 
then launch it 

**Expected behavior**
get cpu info step pass , 

**Screenshots**
2020/03/10 08:54:04 cpu.go:100: resourceutil cpu info getting fail :  open /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq: no such file or director

**Test environment configuration (please complete the following information):**
root@ubuntu18:/var/edge-orchestration/log# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
root@ubuntu18:/var/edge-orchestration/log# uname -a
Linux ubuntu18 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu18:/var/edge-orchestration/log# virt-what
virtualbox
kvm

* Firmware version: (OS type and version, e.g., Ubuntu 14.04, etc.)
* Hardware: (e.g., x86-64, ARM, CPU type, RAM size, etc.)
* Toolchain: (e.g., Docker and Go versions)
* Edge Orchestration Release: (e.g., Alpha, Baobab, Coconut)

**Additional context**

**Comment by suresh-lc** [comment] 2020-03-11 05:52
Looks the file "cpuinfo_max_freq" is missing. And could find that in some machines this file need not be present. And in such cases some suggest to read from /proc/cpuinfo. We will check on this issue and let know.

**Comment by tdrozdovsky** [comment] 2020-03-11 19:32
I came across this problem. Virtual machines do not properly emulate a processor. Therefore, these files that describe the processor are not in the file system. Sometimes I got the idea to write a driver that will emulate them (but I don’t know if it makes sense)

**Comment by suresh-lc** [comment] 2020-03-12 05:42
@AUGxhub " Can you give more details on why you are using home edge orchestration on KVM. We are trying understand your use case and see what role home edge orchestration is playing there. This will give us some clarity on the environments where home edge might be used which would help in resolving the issue.

**Comment by tdrozdovsky** [comment] 2020-03-12 06:16
@suresh-lc  Simple use cases:
1) start of not trusted code is better to do in a virtual machine
2) you can create several virtual machines on the same PC and try how the edge-orchestration works (an ordinary person has one PC)
3) launch under host OS other than Linux

**Comment by AUGxhub** [comment] 2020-03-12 07:07
i find the reason

in src/common/resourceutil/cpu 
func getCPUMaxFreq() (float64, error) {
    f, err := fileOpen("/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq")
    defer f.Close()
    if err != nil {
        return 0.0, err
    }

this does not work on vm , i add a hijack to run it locally , but it may need add patch to support VM env
maybe use /proc/cpuinfo on vm ,

**Comment by suresh-lc** [comment] 2020-03-12 08:19
@tdrozdovsky : I understand the steps he had done and how he got the issue. My question was what was the practical scenario why home edge was being executed in kvm.

**Comment by suresh-lc** [comment] 2020-03-12 08:22
> i find the reason
> 
> in src/common/resourceutil/cpu
> func getCPUMaxFreq() (float64, error) {
> f, err := fileOpen("/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq")
> defer f.Close()
> if err != nil {
> return 0.0, err
> }
> 
> this does not work on vm , i add a hijack to run it locally , but it may need add patch to support VM env
> maybe use /proc/cpuinfo on vm ,

Yes we know this is the cause of the problem. And as i had mentioned earlier, we can probably use /proc/cpuinfo. But home edge currently doesnt support execution in kvm. So wanted to check on use case before we do the changes.

**Comment by MoonkiHong** [comment] 2020-03-12 08:23
@AUGxhub As Suresh pointed out, could you please rectify your practical use cases / scenarios why Home Edge orchestrator was being executed on top of kvm?

**Comment by AUGxhub** [comment] 2020-03-13 14:14
> @AUGxhub As Suresh pointed out, could you please rectify your practical use cases / scenarios why Home Edge orchestrator was being executed on top of kvm?

I try to test how does it oraches running container to different targets, but i don't have many devices, so I make 3 vm on my pc , 

PS, I also find another issue, when I try to make it run default Nginx container, it fail to read out some params (like container name "--name nginx", port expose "-p 8080:80", etc )

PPS, this file not fond on some router also. such as Asus GT-ac5300 router,

**Comment by AUGxhub** [comment] 2020-03-21 11:38
after check ,the --name  not define in container.config , in go-docker api , so , can not assgin name 
other options works

**Comment by suresh-lc** [comment] 2020-03-24 09:54
@AUGxhub : You want --name flag to be added ? And i suppose you want to pass the container name via this flag.

**Comment by tdrozdovsky** [comment] 2020-03-25 19:08
Due to the spread of the COVID-19, we work remotely at home, and therefore I only have one computer, and this made me solve the problem of starting the system on a Virtual Machine.

The `--name` parameter used should be considered separately and in more detail since it affects the security of the Edge Orchestration system. Please create a new issue for this.

**Closed** 2020-03-30 23:52 UTC
Labels: bug
