### ISSUE TITLE
README - private link

### ISSUE THREAD

**Issue by mmiklus** [lf-edge/edge-home-orchestration-go#22] opened 2019-08-08 09:23 UTC
2. Download Docker image
Please download edge-orchestration

I can't access the link "https://github.sec.samsung.net/RS7-EdgeComputing/edge-home-orchestration-go/releases/download/alpha/edge-orchestration.tar"

**Comment by MoonkiHong** [comment] 2019-08-20 04:57
@wansuyoo @jyong2kim Hi, the link in the current README.md directs the internal GitHub which we cannot access right now.

**Comment by wansuyoo** [comment] 2019-09-04 22:35
Hi. fixed the link for image of tar archive to current github release.

**Comment by MoonkiHong** [comment] 2019-09-06 05:20
Thank you for your kind reminder, I have checked out the pending PR request #35 . Once it is approved and merged, I will close this issue! :)

**Comment by MoonkiHong** [comment] 2019-09-16 23:09
@mmiklus The PR has been merged. Please check out and close this issue. :)

**Comment by MoonkiHong** [comment] 2020-03-11 05:58
Since this has been already resolved by merging the related PR #35, we will close this issue. Please let us know if this is reproduced again.

**Closed by MoonkiHong** 2020-03-11 05:58 UTC
